CREATE TABLE CLIENT
(
    `ID`         int(11)      NOT NULL AUTO_INCREMENT,
    `NAME`       varchar(100) NOT NULL,
    `BIRTH_DATE` DATE         NULL,
    `DELETED`    tinyint(1)   NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
);

CREATE TABLE PRODUCT
(
    `ID`          int(11)      NOT NULL AUTO_INCREMENT,
    `SKU`         varchar(500) NOT NULL,
    `NAME`        varchar(100) NOT NULL,
    `DESCRIPTION` varchar(500) NULL,
    `PRICE`       int(11)      NOT NULL,
    `QUANTITY`    int(11)      NOT NULL,
    `DELETED`     tinyint(1)   NOT NULL DEFAULT '0',
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT_ORDER
(
    `ID`             int(11)    NOT NULL AUTO_INCREMENT,
    `ID_CLIENT`      int(11)    NOT NULL,
    `PURCHASE_VALUE` int(11)    NOT NULL,
    `PURCHASE_DATE`  DATE       NULL,
    `DELETED`        tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (ID),
    KEY ORDER_ID_CLIENT_KEY (ID_CLIENT),
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID)
);

CREATE TABLE ORDERED_ITEM
(
    `ID`              int(11) NOT NULL AUTO_INCREMENT,
    `QUANTITY`        int(11) NOT NULL,
    `ID_PRODUCT`      int(11) NOT NULL,
    `ID_CLIENT_ORDER` int(11) NOT NULL,
    PRIMARY KEY (ID),
    KEY ORDERED_ITEM_ID_PRODUCT_KEY (ID_PRODUCT),
    CONSTRAINT FK_ORDERED_ITEM_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID),
    KEY ORDERED_ITEM_ID_ORDER_KEY (ID_CLIENT_ORDER),
    CONSTRAINT FK_ORDERED_ITEM_ORDER FOREIGN KEY (ID_CLIENT_ORDER) REFERENCES CLIENT_ORDER (ID)
);