CREATE TABLE CLIENT
(
    `ID`         int(11)      NOT NULL AUTO_INCREMENT,
    `NAME`       varchar(100) NOT NULL,
    `BIRTH_DATE` DATE         NULL,
    `DELETED`    tinyint(1)   NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
);

CREATE TABLE PRODUCT
(
    `ID`          int(11)      NOT NULL AUTO_INCREMENT,
    `SKU`         varchar(500) NOT NULL,
    `NAME`        varchar(100) NOT NULL,
    `DESCRIPTION` varchar(500) NULL,
    `PRICE`       int(11)      NOT NULL,
    `QUANTITY`    int(11)      NOT NULL,
    `DELETED`     tinyint(1)   NOT NULL DEFAULT '0',
    PRIMARY KEY (ID)
);

CREATE TABLE ORDERED
(
    `ID`             int(11)    NOT NULL AUTO_INCREMENT,
    `ID_CLIENT`      int(11)    NOT NULL,
    `PURCHASE_VALUE` int(11)    NOT NULL,
    `PURCHASE_DATE`  DATE       NULL,
    `DELETED`        tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (ID),
    KEY ORDERED_ID_CLIENT_KEY (ID_CLIENT),
    CONSTRAINT FK_ORDERED_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID)
);

CREATE TABLE ASSOC_PRODUCT_ORDERED
(
    ID_PRODUCT INT NOT NULL,
    ID_ORDERED INT NOT NULL,
    CONSTRAINT FK_ASSOC_PRODUCT_ORDERED
        FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID),
    CONSTRAINT FK_ASSOC_ORDERED_PRODUCT
        FOREIGN KEY (ID_ORDERED) REFERENCES ORDERED (ID)
);
